server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_comp_level 1;
    gzip_min_length 1024;
    gzip_vary on;
    gzip_types
        application/json
        application/octet-stream
        model/gltf+json;
}
